Migrate to null safety and Flame v1rc8
flame-engine/flame_tiled pull request #6
Opened 2021-03-28 07:53 UTC by Akida31

Flame_tiled can now be used from Flame v1 release candidates!

# TODO
update version of `tiled.dart` after it's null safe (for example through [this PR](https://github.com/flame-engine/tiled.dart/pull/19))

2021-03-30 09:28 UTC, Schnurber requested changes
Depending on the new version of tiled (open pull request), we can get rid of most `!`.

2021-03-30 09:28 UTC, Schnurber commented on example/lib/main.dart
> +      comp.x = obj.x!.toDouble();
With my new version for tiled, the `!` is not needed.

2021-03-30 09:28 UTC, Schnurber commented on example/lib/main.dart
> +      comp.y = obj.y!.toDouble();
`!` not necessary

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +    image = await Flame.images.load(map.tilesets[0].image!.source!);
for new tiled: `image = await Flame.images.load(map.tilesets[0].image!.source);`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +    map.layers.where((layer) => layer.visible!).forEach((layer) {
`layer.visible` without `!`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +      layer.tiles!.forEach((tileRow) {
remove `!`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +          if (tile!.gid == 0) {
remove `!`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +              tile.x!.toDouble() * tileSize.width +
remove `!`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +              tile.y!.toDouble() * tileSize.height +
remove `!`

2021-03-30 09:28 UTC, Schnurber commented on lib/tiled.dart
> +            scale: tileSize.width / tile.width!,
remove `!`

2021-05-20 00:15 UTC, sainoba commented
Hi there, thank you for all the hard work.
Is there a timeline of when this PR will hit the pub.dev page??

2021-05-20 07:01 UTC, spydon commented
Hi @sainoba, we just merged a big PR for tiled and that package has to be migrated to nullsafety first and then we can migrate this package, so it is probably some time left unfortunately.

2021-06-04 16:32 UTC, Schnurber commented
@Akida31 you have to update the versions of tiled to `tiled: 0.7.0` and you have to create a pull request from your **dev** Branch not master!

2021-06-23 11:42 UTC, loothood commented
Hi, thank you for the repository and for your hard work.
When can we use the null safety version of the package?

2021-06-23 18:52 UTC, Akida31 commented
Hey, I don't use flame currently so I won't develop this further. At the moment there is development on nullsafety in this repo: https://github.com/Schnurber/flame_tiled/tree/dev
This PR is basically only waiting for the other work and then it will be closed. It is still open to show that there is some work on this topic.

2021-07-08 07:38 UTC, Akida31 commented
Will be done with #10

2021-07-08 07:38 UTC, closed without merging